import os
import sys
import sphinx_rtd_theme

# -- Project information -----------------------------------------------------

project = 'Measurement Management System for Gas Stations'
author = 'Your Name Here'

# The full version, including alpha/beta/rc tags
release = '1.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx_rtd_theme',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'MeasurementManagementSystemDoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}

latex_documents = [
    (master_doc, 'MeasurementManagementSystem.tex', 'Measurement Management System Documentation',
     'Your Name Here', 'manual'),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'measurementmanagement', 'Measurement Management System Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'MeasurementManagementSystem', 'Measurement Management System Documentation',
     author, 'MeasurementManagementSystem', 'One line description of project.',
     'Miscellaneous'),
]

# -- Extension configuration -------------------------------------------------

# -- Options for autodoc extension -------------------------------------------

# List of modules to be mocked up
autodoc_mock_imports = []

# -- Options for Napoleon extension ------------------------------------------

# Include private methods in documentation
napoleon_include_private_with_doc = True

# Add support for Google-style docstrings
napoleon_google_docstring = True
